### ISSUE TITLE
New project name poll

### ISSUE THREAD

**Issue by psprint** [zdharma/zinit#181]
Hello!
I'm thinking about changing the name for the project. The propositions are the comments to the issue. Vote by thumbs-up or thumbs-down emoji. You can also add your own propositions. You can vote multiple times. For a discussion, please use this [reddit post](https://www.reddit.com/r/zsh/comments/dgw2ss/newname_poll_for_the_zplugin_project/). However for an explaining of why the proposed name is good you can use the comment.

**Update:** The thread is effectively closed as a new 2nd voting round has been posted (#235). However, this thread can be used for discussion on the name change.

**Comment by psprint** [comment]
ion

**Comment by psprint** [comment]
proxima

**Comment by psprint** [comment]
echelon

**Comment by psprint** [comment]
hyper

**Comment by psprint** [comment]
solar

**Comment by psprint** [comment]
velocity

**Comment by psprint** [comment]
jupiter

**Comment by psprint** [comment]
prodigy

**Comment by psprint** [comment]
tensor

**Comment by psprint** [comment]
hyper

**Comment by psprint** [comment]
momentum

**Comment by psprint** [comment]
atlantis

**Comment by psprint** [comment]
future

**Comment by psprint** [comment]
amphiboly

**Comment by adberard** [comment]
zsh plugin manager, zpm

**Comment by Seirdy** [comment]
zplugin

**Comment by huequica** [comment]
z(plug)in -> zin

**Comment by CoskunSunali** [comment]
pluginz

**Comment by davidosomething** [comment]
`supply` -> `zupply`

**Comment by robobenklein** [comment]
zygo

**Comment by robobenklein** [comment]
zircon

**Comment by robobenklein** [comment]
zenith

**Comment by psprint** [comment]
zeal

**Comment by psprint** [comment]
zeta

**Comment by psprint** [comment]
zesty

**Comment by psprint** [comment]
lambda

**Comment by crivotz** [comment]
zitro

**Comment by Cueball** [comment]
zinit

as per the (current) top comment in the [/r/zsh sub post](https://www.reddit.com/r/zsh/comments/dgw2ss/newname_poll_for_the_zplugin_project/f3fru4i)

**Comment by Seirdy** [comment]
zpackage

This is more than a shell script plugin manager; it's basically a generic (primarily
source-based) *package* manager at this point, optimized for very simple one-line
recipes for which Nix/Gentoo would be overkill.

**Comment by black7375** [comment]
z(sh) pl(ugin) -> zpl

**Comment by psprint** [comment]
Epsilon

**Comment by olfway** [comment]
zpack

a bit shorter than zpackage

**Comment by DundarGoc** [comment]
zpac

**Comment by DundarGoc** [comment]
zell

**Comment by DundarGoc** [comment]
zphere

**Comment by DundarGoc** [comment]
ztar

**Comment by j0hnm4r5** [comment]
Frozen (ice)

**Comment by j0hnm4r5** [comment]
Zap

**Comment by j0hnm4r5** [comment]
Sash

**Comment by j0hnm4r5** [comment]
zpick

**Comment by j0hnm4r5** [comment]
sodapop

(sodapop ice, sodapop light)

**Comment by j0hnm4r5** [comment]
Boreal

(Meaning far northern; a climate with long winters with short summers. As in aurora borealis, which is “light”, and often happens where there’s “ice”).

**Comment by agkozak** [comment]
`vanilla`

It's a popular flavor, and then there's always [Vanilla Ice](http://www.vanillaice.com/), so people could have fun typing `vanilla ice silent` etc. etc.

**Comment by agkozak** [comment]
> 
> 
> z(plug)in -> zin

Way too much like [zim](https://github.com/zimfw/zimfw), another ZSH framework.

**Comment by agkozak** [comment]
`celer`

Latin for "fast."

**Comment by DundarGoc** [comment]
Zphere

My reasoning:

Name not taken.

Abstract enough name that it doesn't give the impression that it only does one thing (which I interpreted is one of the main reasons for the name change).

Easy to pronounce.

Bonus: starts with a "z".

**Comment by rongmu** [comment]
The current `zplg` / `zpl` aliases are pretty nice.

**Comment by indolering** [comment]
zpack - Shorter than zpackage and less cute than zpac.

**Comment by indolering** [comment]
`zpak`, which is also the term used for the (AFAIK) frontline antibiotic [Zithromax](https://www.drugs.com/mtm/zithromax-z-pak.html).

**Comment by itai33** [comment]
zoom

-leans into the plugin being fast
-seems to mainly refer to a video sharing app so it wont really overlap, since people will search zsh zoom
-sounds fun
-short

**Comment by tke** [comment]
`zupple`
* hints at the flexible nature of the tool
* can still retain the `zpl` alias people are attached to

**Comment by indolering** [comment]
@psprint Are you going to change it or just run the poll forever?  I would definitely change the name before submitting for inclusion to any distro...

**Comment by j0hnm4r5** [comment]
See #235

**Comment by indolering** [comment]
@psprint Update the ticket to include a link to the second round and close this thread.

**Comment by psprint** [comment]
For me, the best name would be either `zenith`,`zupply` or `zsphere`. The first one has an interesting firm-standing trait, the second one a very interesting entertainment trait and the third one an interesting sophistication/advancement trait. The name `zinit` is somewhat without any traits, but I'm telling that this must be its indirect trait and since the community likes it, then it has to be the best choice.

**Comment by dg1727** [comment]
I'd like to share some thoughts on this.  I realise that any major change in the direction this discussion is going is unlikely at this late time.  If my ideas are unpopular, I won't feel bad.  

I'm not keen on "zinit" because it's so generic:  
* It sounds like a name that should be reserved for the Zsh developers to use.  
* To me, it doesn't connote "package manager" or "customise" or "speedup".  

First I will list some candidates which wouldn't seem to work, mainly because of name collisions.  Then, in separate postings as others have done earlier, I'll suggest a few (5 I have in mind at the moment, although some are better than others) that don't seem to be name collisions.  

I will list the names in each category ("not great" and "maybe") in alphabetical order.  My criteria on "is a given objection severe enough to disqualify the name?" are arbitrary, and other people could easily disagree with me.  

BTW, the existing project "prezto" is an example of a brilliant name for this kind of software - it's short, easy to pronounce, and fun, and it contains a Z.  

Several of the following are quite good, and it's a shame that there are reasons not to use them:  

Name | Objection 
-|-
blazt | a professional Call of Duty player - also already used on GitHub 
froz (as in "frob" meaning "to work with something/to customise") | a brand of ice cream 
pizza | there is already such a repo on GitHub 
slurpz (like the former "yum" Linux package manager) | awkward to pronounce 
zap | there is already a well-known user called "zzapper" 
zat ("Zsh Addons Tool" or "what zat?" :) | there is already such a repo on GitHub 
zenith (one of my favourites) | commercial software company 
zest ("orange zest" could be used to flavour a beverage) | commercial software company 
zeta | commercial software company 
zlurp | software company 
zoda (beverage + Hitchhiker's Guide reference + evocative of "Yoda") | a video-game villain; also a fashion accessory company 
zola (like the beverage "cola" and the writer Zola) | commercial software company 
zolar (like "solar" that was already suggested) | sounds like a fantasy character :)
zolo (like "Han Solo" :) | a brand of headphones sold to tech-savvy users, i.e., possible market overlap among zsh users
zolt | a laptop charger 
zon | a guitar company, and a pharmacy-drug company 
zoom | I have a reservation about **itai33**'s belief that this name collision wouldn't be a problem; "zoom" is a trademark in a market segment likely to be shopped by zsh users (cloud videoconferencing)
zoop | software company, video game, and TV series 
zorb ("Z Orb" [Z World]) | but "absorb" might not be a suitable connotation 
zpak | Azithromycin is believed to cause heart problems sometimes 
zphere | contrary to **DundarGoc**'s comment, I'm concerned that many people may find this hard to pronounce
zpick | could seem weird since one possible syntax is like "zpick pick" 
zply | there is already such a repo on GitHub - & highly ambiguous pronunciation :-) - "zupply" and "zplay" as **davidosomething** suggested, plus "z-ply" as in "two-ply cloth"
zum | a transportation company (pronounced "zoom").  Also a brand of soap.  
zup (Zsh power-Up + "what'z up?" :) | game on Steam, plus a brand of adventure-sports gear 
zupple | I like the meaning as in "flexible," but I think the word sounds a bit odd 
zupply | already taken, as **davidosomething** has pointed out
zurbo ("Z Turbo") | there is already such a repo on GitHub

**Comment by dg1727** [comment]
**citruz** (respelling of "citrus" fruit)
* would fit the "beverage" theme 
* currently a brand of fishing tackle 
  * I don't think this would be considered a name collision 
  * to get a package from the network is distantly like fishing, anyway 
* this would lend itself to its own sub-theme along with "beverages" (like how Linuxbrew also has a beverage theme with "bottles," "casks," etc.); for example, snippets or what-have-you could be called "zests" (which also happens to have a Z in it :)

**Comment by dg1727** [comment]
**graz** (city in Austria) 
* there is precedent for open-source software named after cities:  Cairo, Canberra, etc. 
* Get and Reconfigure Addons for Zsh 
* like "grace" as in "this will grace your Zsh"

**Comment by dg1727** [comment]
**mrzpn** (as in "marzipan" which is a candy ingredient made of sugar & almonds) 
* "Manage and Reconfigure Zsh Packages from the Network" 
* would be amusing:
  * " Mr. Zippin' " ("zip" connotes speed & software packages)
  * "I'm nuts [as in "marzipan"] about mrzpn!" 
  * has no vowels, like "grml" which is the name of a Linux distro that emphasises zsh

**Comment by dg1727** [comment]
**zop** (according to Wiktionary, to some Western Europeans this could mean "liquid" or "juice," which would fit the "beverage" theme) 
* a GitHub repo, but that author might give permission to use the name 
* "Zsh OPtimisation" 
* "Zsh Optional Packages"

**Comment by dg1727** [comment]
**zow** (as in "wow!")
* a Polish anti-Nazi organization during WW2 
* a trade show which is a "meeting place for suppliers to the furniture & interior design industries" 
  * I don't think that would be a name collision, and anyway:  
  * the open-source nature of this zsh project makes it like a "meeting place" 
  * probably many zsh users are software engineers, who make the "furniture" of people's digital lives
* there should be an FAQ that the preferred pronunciation is like "wow" (not rhyming with "toe")

**Comment by robobenklein** [comment]
I didn't even realize that `zenith` was a company name (or is "Zenith Electronics" the collision?), I did search it but it was a real english word (meaning the high point or peak during some time), so I don't think we'd have to worry about copyright or trademark violations.

There are a few repos on github named "zenith", but none of them seem to directly relate to any kind of shell. (Most use the word for it's literal definition, relating to the sun's peak)

Personally I would like to explore more options that don't necessarily start with Z, but for Zsh projects it makes sense that it's the dominant suggestion.

**Comment by psprint** [comment]
What do you guys think about calling the project "Dharma Initiative Plugin Manager"? The `zinit` would then state for the Initiative and `zdharma` for Dharma, like the original reddit comment suggested?

**Comment by crivotz** [comment]
In my opinion, it is also necessary to think about how easy it is to find information by carrying out a search. Names such as `zplugin` or `zinit` come back more false positive in the results than using more specific names

For example a name like `z-Ice` avoid misunderstandings (I added the hyphen because there is a city called Zice)

For scruple I search `zitro` (which I had proposed) and I saw that there is a company that produces games.

**Comment by dg1727** [comment]
@robobenklein The potential "zenith" name collision:  I searched on "zenith software" and found zenithsoft.com which I haven't looked at in detail.
