### ISSUE TITLE
How to use binary in sub folder with for-syntax?

### ISSUE THREAD

**Issue by x1a0** [zdharma/zinit#237]
With the original syntax it works:
```zsh
zplugin ice from"gh-r" as"program" pick"**/circleci"
zplugin load CircleCI-Public/circleci-cli
```

However I cannot figure out how to do it with `for-syntax`.
I've tried:
```zsh
zplugin wait lucid from"gh-r" for \
    sbin"circleci" CircleCI-Public/circleci-cli
```
```zsh
zplugin wait lucid from"gh-r" for \
    sbin"**/circleci" CircleCI-Public/circleci-cli
```
```zsh
zplugin wait lucid from"gh-r" pick"**/circleci" for \
    sbin"circleci" CircleCI-Public/circleci-cli
```

Thanks!

**Comment by psprint** [comment]
I think that the problem is:
- no as"program" in the for-syntax version,
- OR, in the alternate `sbin''` version, no `zplg delete CircleCI-Public/circleci-cli` before running the command – the `sbin''` ice is being activated during installation; plus the z-a-bin-gem-node annex should be loaded first.
