### ISSUE TITLE
How to avoid extending $PATH with git-now

### ISSUE THREAD

**Issue by hpmcz** [zdharma/zinit#266]
Hi
 I'm a new Zinit user and I've incorporated the [Git extensions](https://github.com/zdharma/zinit#extending-git) from the README into my `zshrc`, however, with a slight change – instead of using `as"program"`, I'm installing the `git-now` extension with `make"install …"`:

 ```zsh 
zinit wait=3 lucid as=null make="install PREFIX=$ZPFX" for iwata/git-now
  ```
 
 The problem is that git-now's Makefile doesn't respect PREFIX and installs to the `/usr/local/…` prefix.
 
 Is there any way to install it under $ZPFX and/or(in general) to avoid modifying $PATH?

**Comment by psprint** [comment]
The best method would be to first load [Bin-Gem-Node](https://github.com/zinit-zsh/z-a-bin-gem-node) annex (a Zinit [extension](https://zdharma.org/zinit/wiki/Annexes/)) and then to expose the `git-now` script/binary via *shim*, i.e.: a forwarder script that has the path to the shielded binary hard-coded inside itself. Shims are created automatically via `sbin''` ice, you can:

- pass nothing to the ice, i.e.:

  ```zsh
  zinit sbin for iwata/git-now
  ```

  This will work because when the ice is empty then an automatic searching for a binary is performed, which works as follows:
    * first a check for the trailing component of the `id-as` ice is being performed, e.g.: `id_as'exts/git-my'` → it'll check if a file `git-my` exists and if yes, create the shim `git-my`,
    * if no success, then a check the plugin name is done, e.g.: for `paulirish/git-open` it'll check if a file `git-open` exists and if yes, create the shim `git-open`,
    * for snippets, the trailing component of the snippet URL is being took instead of the plugin name,,
    * then, if no success, it'll take the name of the alphabetically first executable file, if any,
    * if still no success, the automatic resolution gives up and a warning message is emitted without creating the shim(s).

- pass `git-my` to the ice, i.e.:

  ```zsh
  zinit sbin=git-my for iwata/git-now
  ```
  This instructs Bin-Gem-Node annex to create the shim for the provided file. **Note:** the `sbin''` argument can be a pattern, e.g.: `zinit sbin'bin/*' gem'jekyll' for zdharma/null` will create the shims for all binaries of the jekyll gem (the example slightly runs forward and introduces the `gem''` ice, another feature of Bin-Gem-Node – refer to the annex's README for more information).

That's it. Of course, you would probably also want Turbo, so the full command would be e.g.:

```zsh
zinit wait=1 lucid sbin for iwata/git-my
```

**Comment by hpmcz** [comment]
Thank you for that answer, it is very helpful.
