### ISSUE TITLE
zinit fails to load / light-load any plugins on Termux

### ISSUE THREAD

**Issue by xPMo** [zdharma/zinit#267]
After bisecting, this commit is the culprit:

```
commit f6145dff242c5684f7abea2c26b3c9f184eaa85b
Author: SG <sgniazdowski@gmail.com>
Date:   Wed Jan 29 14:20:37 2020 +0100

    zinit: Use zselect for a more predictable sleep time

 1 file changed, 4 insertions(+), 3 deletions(-)
```

Since all the modules are static, some (like zsh/zselect) not enabled in Termux's zsh distribution. I've opened an issue at termux/termux-packages#4939 to address this and opened this [NOT-OUR-BUG] issue here in case anyone else wants to know what is happening. I will close when upstream is resolved.

**Comment by romkatv** [comment]
That sucks :-/

It means half of p10k doesn't work on Termux and no one told me.

**Comment by psprint** [comment]
I've reverted the commit. Can reapply when Termux enables the module.

**Comment by xPMo** [comment]
I dug into it and [made a PR](https://github.com/termux/termux-packages/pull/4940).

**Comment by xPMo** [comment]
The PR is merged and the update made its way to my phone. @psprint You can revert and close this.

**Comment by romkatv** [comment]
Are you a single person?

**Comment by xPMo** [comment]
I'm a math grad student with a light course load this semester.

**Comment by romkatv** [comment]
Must be very light indeed. Good for us! Thanks for taking care of this.

**Comment by psprint** [comment]
Ok, I've reverted the original commit back. Thanks!

**Comment by psprint** [comment]
Turns out that I've had to revert the patch again. This time it's not about `zselect`, but about triggering the zle-F-handler run:

1. With the revert:
    ```zsh
    exec {ANFD}< <(LANG=C command sleep 0.0002; builtin print run;)
    ```
![2020-02-25-150156_1041x709_scrot](https://user-images.githubusercontent.com/6049288/75254116-239cf080-57e0-11ea-9a5d-7b88c28f3207.png)

2. Without the revert:
    ```zsh
    exec {ANFD}< /dev/null
    ```
![2020-02-25-150028_1037x717_scrot](https://user-images.githubusercontent.com/6049288/75254205-4af3bd80-57e0-11ea-9ce3-0d9d94fa5d79.png)

Pressing keyboard keys was greatly lowering the effects of the bug. @romkatv  I saw that you use the `…</dev/null` method, maybe it's worth reconsidering.

**Comment by romkatv** [comment]
> @romkatv I saw that you use the `…</dev/null` method, maybe it's worth reconsidering.

Thanks for the heads up. Can you describe the bug without referring to zinit? Can you provide a self-contained code snippet that demonstrates it?

**Comment by psprint** [comment]
It'll be worse with the snippet (lack of time; I'll try later today), however, the bug (or maybe `zle -F` behavior) appears to be: triggering the `zle -F` handler via redirection to `/dev/null` and not via an output printed to the file descriptor seems to trigger the `-F`` handler more slowly or not triggering it at all.

**Comment by romkatv** [comment]
Cannot reproduce from this description:

```zsh
function schedule() {
  emulate -L zsh
  local -i fd
  exec {fd}</dev/null
  zle -F $fd resume
}

function resume() {
  emulate -L zsh
  zle -F $1
  exec {1}>&-
  (( ++count ))
  local -F seconds='EPOCHREALTIME - start_time'
  if (( seconds < 3 )); then
    schedule
  else
    zle -I
    local -i count_per_second='count / seconds'
    typeset -p count seconds count_per_second
    unset count start_time
  fi
}

() {
  emulate -L zsh
  zmodload zsh/datetime
  schedule
  typeset -gi count=0
  typeset -gF start_time=EPOCHREALTIME
}
```

Output:

```text
typeset -g -i count=57624
typeset -F seconds=3.0000338554
typeset -i count_per_second=19207
```

While the code is running for 3 seconds, keyboard input is not blocked.

Since you have code that doesn't behave the way you expect, and you know that code better than anyone else, you are in the best position to reduce it. Your guess that `zle -F` has a bug might be true, or it might be false. The only way to find out is to understand why the code behaves the way it does.
