### ISSUE TITLE
Install script isn't using custom path's

### ISSUE THREAD

**Issue by cour64** [zdharma/zinit#443]
You can customize Zinit paths as mentioned [here](https://github.com/zdharma/zinit#customizing-paths). Except when you run the [install script ](https://github.com/zdharma/zinit/blob/master/doc/install.sh) the variable `ZINIT_HOME` is used instead of `ZINIT[HOME_DIR]`.

Here's the culprit:
https://github.com/zdharma/zinit/blob/857d6fb6b46a4043f772315e8184c1b7e22c235e/doc/install.sh#L7-L10

I'm not sure if it's intentional but I expected to be used `ZINIT[HOME_DIR]` instead of `ZINIT_HOME`. If this is intentional how does one set a custom home dir for Zinit and plugins to install to?

**Versions:**
 - $ZSH_VERSION == 3.5
 - Operating system name and version (uname -a): Ubuntu 20.04

**Comment by NICHOLAS85** [comment]
I'm pretty sure the install script is the only place where `ZINIT_HOME` is used. You can simply set `ZINIT_HOME` to the same value as `ZINIT[HOME_DIR]` before running the script and it should respect this value. As for why the install script uses a regular variable instead of the associative array used by Zinit elsewhere. The install script is written in (almost) POSIX sh which doesn't support associative arrays.

**Comment by cour64** [comment]
That makes sense I wasn't aware of POSIX sh's lack of support for associative arrays thanks, closing this.
